unit RedeemerHypertextColorsCSS;

interface

uses
  RedeemerHypertextColors;

const
  CSSColors: array[0..147] of TColorName = ((Color: $00FFF8F0; Name: 'aliceblue'),
                                           (Color: $00D7EBFA; Name: 'antiquewhite'),
                                           (Color: $00FFFF00; Name: 'aqua'), // Nachtrag 03.02.17
                                           (Color: $00D4FF7F; Name: 'aquamarine'),
                                           (Color: $00FFFFF0; Name: 'azure'),
                                           (Color: $00DCF5F5; Name: 'beige'),
                                           (Color: $00C4E4FF; Name: 'bisque'),
                                           (Color: $00000000; Name: 'black'),
                                           (Color: $00CDEBFF; Name: 'blanchedalmond'),
                                           (Color: $00FF0000; Name: 'blue'),
                                           (Color: $00E22B8A; Name: 'blueviolet'),
                                           (Color: $002A2AA5; Name: 'brown'),
                                           (Color: $0087B8DE; Name: 'burlywood'),
                                           (Color: $00A09E5F; Name: 'cadetblue'),
                                           (Color: $0000FF7F; Name: 'chartreuse'),
                                           (Color: $001E69D2; Name: 'chocolate'),
                                           (Color: $00507FFF; Name: 'coral'),
                                           (Color: $00ED9564; Name: 'cornflowerblue'),
                                           (Color: $00DCF8FF; Name: 'cornsilk'),
                                           (Color: $003C14DC; Name: 'crimson'), // Nachtrag 03.02.17
                                           (Color: $00FFFF00; Name: 'cyan'),
                                           (Color: $008B0000; Name: 'darkblue'),
                                           (Color: $008B8B00; Name: 'darkcyan'),
                                           (Color: $000B86B8; Name: 'darkgoldenrod'),
                                           (Color: $00A9A9A9; Name: 'darkgray'),
                                           (Color: $00006400; Name: 'darkgreen'),
                                           (Color: $00A9A9A9; Name: 'darkgrey'),
                                           (Color: $006BB7BD; Name: 'darkkhaki'),
                                           (Color: $008B008B; Name: 'darkmagenta'),
                                           (Color: $002F6B55; Name: 'darkolivegreen'),
                                           (Color: $00008CFF; Name: 'darkorange'),
                                           (Color: $00CC3299; Name: 'darkorchid'),
                                           (Color: $0000008B; Name: 'darkred'),
                                           (Color: $007A96E9; Name: 'darksalmon'),
                                           (Color: $008FBC8F; Name: 'darkseagreen'),
                                           (Color: $008B3D48; Name: 'darkslateblue'),
                                           (Color: $004F4F2F; Name: 'darkslategray'),
                                           (Color: $004F4F2F; Name: 'darkslategrey'),
                                           (Color: $00D1CE00; Name: 'darkturquoise'),
                                           (Color: $00D30094; Name: 'darkviolet'),
                                           (Color: $009314FF; Name: 'deeppink'),
                                           (Color: $00FFBF00; Name: 'deepskyblue'),
                                           (Color: $00696969; Name: 'dimgray'),
                                           (Color: $00696969; Name: 'dimgrey'),
                                           (Color: $00FF901E; Name: 'dodgerblue'),
                                           (Color: $002222B2; Name: 'firebrick'),
                                           (Color: $00F0FAFF; Name: 'floralwhite'),
                                           (Color: $00228B22; Name: 'forestgreen'),
                                           (Color: $00FF00FF; Name: 'fuchsia'), // Nachtrag 03.02.17
                                           (Color: $00DCDCDC; Name: 'gainsboro'),
                                           (Color: $00FFF8F8; Name: 'ghostwhite'),
                                           (Color: $0000D7FF; Name: 'gold'),
                                           (Color: $0020A5DA; Name: 'goldenrod'),
                                           (Color: $00808080; Name: 'gray'),
                                           (Color: $00008000; Name: 'green'),
                                           (Color: $002FFFAD; Name: 'greenyellow'),
                                           (Color: $00808080; Name: 'grey'),
                                           (Color: $00F0FFF0; Name: 'honeydew'),
                                           (Color: $00B469FF; Name: 'hotpink'),
                                           (Color: $005C5CCD; Name: 'indianred'),
                                           (Color: $0082004B; Name: 'indigo'), // Nachtrag 03.02.17
                                           (Color: $00F0FFFF; Name: 'ivory'),
                                           (Color: $008CE6F0; Name: 'khaki'),
                                           (Color: $00FAE6E6; Name: 'lavender'),
                                           (Color: $00F5F0FF; Name: 'lavenderblush'),
                                           (Color: $0000FC7C; Name: 'lawngreen'),
                                           (Color: $00CDFAFF; Name: 'lemonchiffon'),
                                           (Color: $00E6D8AD; Name: 'lightblue'),
                                           (Color: $008080F0; Name: 'lightcoral'),
                                           (Color: $00FFFFE0; Name: 'lightcyan'),
                                           (Color: $00D2FAFA; Name: 'lightgoldenrodyellow'),
                                           (Color: $00D3D3D3; Name: 'lightgray'),
                                           (Color: $0090EE90; Name: 'lightgreen'),
                                           (Color: $00D3D3D3; Name: 'lightgrey'),
                                           (Color: $00C1B6FF; Name: 'lightpink'),
                                           (Color: $007AA0FF; Name: 'lightsalmon'),
                                           (Color: $00AAB220; Name: 'lightseagreen'),
                                           (Color: $00FACE87; Name: 'lightskyblue'),
                                           (Color: $00998877; Name: 'lightslategray'),
                                           (Color: $00998877; Name: 'lightslategrey'),
                                           (Color: $00DEC4B0; Name: 'lightsteelblue'),
                                           (Color: $00E0FFFF; Name: 'lightyellow'),
                                           (Color: $0000FF00; Name: 'lime'),
                                           (Color: $0032CD32; Name: 'limegreen'),
                                           (Color: $00E6F0FA; Name: 'linen'),
                                           (Color: $00FF00FF; Name: 'magenta'),
                                           (Color: $00000080; Name: 'maroon'),
                                           (Color: $00AACD66; Name: 'mediumaquamarine'),
                                           (Color: $00CD0000; Name: 'mediumblue'),
                                           (Color: $00D355BA; Name: 'mediumorchid'),
                                           (Color: $00DB7093; Name: 'mediumpurple'),
                                           (Color: $0071B33C; Name: 'mediumseagreen'),
                                           (Color: $00EE687B; Name: 'mediumslateblue'),
                                           (Color: $009AFA00; Name: 'mediumspringgreen'),
                                           (Color: $00CCD148; Name: 'mediumturquoise'),
                                           (Color: $008515C7; Name: 'mediumvioletred'),
                                           (Color: $00701919; Name: 'midnightblue'),
                                           (Color: $00FAFFF5; Name: 'mintcream'),
                                           (Color: $00E1E4FF; Name: 'mistyrose'),
                                           (Color: $00B5E4FF; Name: 'moccasin'),
                                           (Color: $00ADDEFF; Name: 'navajowhite'),
                                           (Color: $00800000; Name: 'navy'),
                                           (Color: $00E6F5FD; Name: 'oldlace'),
                                           (Color: $00008080; Name: 'olive'), // Nachtrag 03.02.17
                                           (Color: $00238E6B; Name: 'olivedrab'),
                                           (Color: $0000A5FF; Name: 'orange'),
                                           (Color: $000045FF; Name: 'orangered'),
                                           (Color: $00D670DA; Name: 'orchid'),
                                           (Color: $00AAE8EE; Name: 'palegoldenrod'),
                                           (Color: $0098FB98; Name: 'palegreen'),
                                           (Color: $00EEEEAF; Name: 'paleturquoise'),
                                           (Color: $009370DB; Name: 'palevioletred'),
                                           (Color: $00D5EFFF; Name: 'papayawhip'),
                                           (Color: $00B9DAFF; Name: 'peachpuff'),
                                           (Color: $003F85CD; Name: 'peru'),
                                           (Color: $00CBC0FF; Name: 'pink'),
                                           (Color: $00DDA0DD; Name: 'plum'),
                                           (Color: $00E6E0B0; Name: 'powderblue'),
                                           (Color: $00800080; Name: 'purple'),
                                           (Color: $00993366; Name: 'rebeccapurple'), // Nachtrag 25.02.21
                                           (Color: $000000FF; Name: 'red'),
                                           (Color: $008F8FBC; Name: 'rosybrown'),
                                           (Color: $00E16941; Name: 'royalblue'),
                                           (Color: $0013458B; Name: 'saddlebrown'),
                                           (Color: $007280FA; Name: 'salmon'),
                                           (Color: $0060A4F4; Name: 'sandybrown'),
                                           (Color: $00578B2E; Name: 'seagreen'),
                                           (Color: $00EEF5FF; Name: 'seashell'),
                                           (Color: $002D52A0; Name: 'sienna'),
                                           (Color: $00C0C0C0; Name: 'silver'),
                                           (Color: $00EBCE87; Name: 'skyblue'),
                                           (Color: $00CD5A6A; Name: 'slateblue'),
                                           (Color: $00908070; Name: 'slategray'),
                                           (Color: $00908070; Name: 'slategrey'),
                                           (Color: $00FAFAFF; Name: 'snow'),
                                           (Color: $007FFF00; Name: 'springgreen'),
                                           (Color: $00B48246; Name: 'steelblue'),
                                           (Color: $008CB4D2; Name: 'tan'),
                                           (Color: $00808000; Name: 'teal'), // Nachtrag 03.02.17
                                           (Color: $00D8BFD8; Name: 'thistle'),
                                           (Color: $004763FF; Name: 'tomato'),
                                           (Color: $00D0E040; Name: 'turquoise'),
                                           (Color: $00EE82EE; Name: 'violet'),
                                           (Color: $00B3DEF5; Name: 'wheat'),
                                           (Color: $00FFFFFF; Name: 'white'),
                                           (Color: $00F5F5F5; Name: 'whitesmoke'),
                                           (Color: $0000FFFF; Name: 'yellow'),
                                           (Color: $0032CD9A; Name: 'yellowgreen'));

implementation

end.
